var searchData=
[
  ['s_20new_0',['What&apos;s New',['../whatsnew.html',1,'']]],
  ['safe_1',['SAFE',['../enumcom_1_1cujo_1_1safebrowsing_1_1_s_b_types_1_1_safe_browsing_safe_network_override.html#a89ac541769049a33c3dfcf071a1743cd',1,'com::cujo::safebrowsing::SBTypes::SafeBrowsingSafeNetworkOverride']]],
  ['safebrowsing_2',['SafeBrowsing',['../classcom_1_1cujo_1_1safebrowsing_1_1_safe_browsing.html',1,'com.cujo.safebrowsing.SafeBrowsing'],['../classcom_1_1cujo_1_1safebrowsing_1_1_safe_browsing.html#a92a40f8602ef211d6110143c67d7a871',1,'com.cujo.safebrowsing.SafeBrowsing.SafeBrowsing()']]],
  ['safebrowsing_20sdk_3',['Initializing the Safebrowsing SDK',['../sdkinit.html',1,'']]],
  ['safebrowsing_20sdk_20for_20android_4',['Introduction to the Cujo Safebrowsing SDK for Android',['../index.html',1,'']]],
  ['safebrowsing_2ejava_5',['SafeBrowsing.java',['../_safe_browsing_8java.html',1,'']]],
  ['safebrowsingblock_6',['SafeBrowsingBlock',['../classcom_1_1cujo_1_1safebrowsing_1_1_s_b_types_1_1_safe_browsing_block.html',1,'com::cujo::safebrowsing::SBTypes']]],
  ['safebrowsingconnecterror_7',['SafeBrowsingConnectError',['../classcom_1_1cujo_1_1safebrowsing_1_1_s_b_types_1_1_safe_browsing_connect_error.html',1,'com::cujo::safebrowsing::SBTypes']]],
  ['safebrowsingerror_8',['SafeBrowsingError',['../enumcom_1_1cujo_1_1safebrowsing_1_1_s_b_types_1_1_safe_browsing_error.html',1,'com::cujo::safebrowsing::SBTypes']]],
  ['safebrowsinghandler_9',['SafeBrowsingHandler',['../classcom_1_1cujo_1_1safebrowsing_1_1_safe_browsing_handler.html',1,'com::cujo::safebrowsing']]],
  ['safebrowsinghandler_2ejava_10',['SafeBrowsingHandler.java',['../_safe_browsing_handler_8java.html',1,'']]],
  ['safebrowsingloglevel_11',['SafeBrowsingLogLevel',['../enumcom_1_1cujo_1_1safebrowsing_1_1_s_b_types_1_1_safe_browsing_log_level.html',1,'com::cujo::safebrowsing::SBTypes']]],
  ['safebrowsinglookuperror_12',['SafeBrowsingLookupError',['../classcom_1_1cujo_1_1safebrowsing_1_1_s_b_types_1_1_safe_browsing_lookup_error.html',1,'com::cujo::safebrowsing::SBTypes']]],
  ['safebrowsingmessagehandler_13',['SafeBrowsingMessageHandler',['../classcom_1_1cujo_1_1safebrowsing_1_1_safe_browsing_message_handler.html',1,'com::cujo::safebrowsing']]],
  ['safebrowsingmessagehandler_2ejava_14',['SafeBrowsingMessageHandler.java',['../_safe_browsing_message_handler_8java.html',1,'']]],
  ['safebrowsingmessageparsing_2ejava_15',['SafeBrowsingMessageParsing.java',['../_safe_browsing_message_parsing_8java.html',1,'']]],
  ['safebrowsingsafenetworkoverride_16',['SafeBrowsingSafeNetworkOverride',['../enumcom_1_1cujo_1_1safebrowsing_1_1_s_b_types_1_1_safe_browsing_safe_network_override.html',1,'com::cujo::safebrowsing::SBTypes']]],
  ['safebrowsingsettings_17',['SafeBrowsingSettings',['../classcom_1_1cujo_1_1safebrowsing_1_1_s_b_types_1_1_safe_browsing_settings.html',1,'com::cujo::safebrowsing::SBTypes']]],
  ['safebrowsingstats_18',['SafeBrowsingStats',['../classcom_1_1cujo_1_1safebrowsing_1_1_s_b_types_1_1_safe_browsing_stats.html',1,'com::cujo::safebrowsing::SBTypes']]],
  ['sbtypes_19',['SBTypes',['../classcom_1_1cujo_1_1safebrowsing_1_1_s_b_types.html',1,'com::cujo::safebrowsing']]],
  ['sbtypes_2ejava_20',['SBTypes.java',['../_s_b_types_8java.html',1,'']]],
  ['sdk_21',['Initializing the Safebrowsing SDK',['../sdkinit.html',1,'']]],
  ['sdk_20for_20android_22',['Introduction to the Cujo Safebrowsing SDK for Android',['../index.html',1,'']]],
  ['sdkinit_2edox_23',['sdkinit.dox',['../sdkinit_8dox.html',1,'']]],
  ['setconfig_24',['setConfig',['../classcom_1_1cujo_1_1safebrowsing_1_1_safe_browsing.html#af4f39f93afbfa7ea52adc615d88b594c',1,'com::cujo::safebrowsing::SafeBrowsing']]],
  ['setenabled_25',['setEnabled',['../classcom_1_1cujo_1_1safebrowsing_1_1_safe_browsing.html#aab5501e662235002c5fc5128b0704acc',1,'com::cujo::safebrowsing::SafeBrowsing']]],
  ['sethandler_26',['setHandler',['../classcom_1_1cujo_1_1safebrowsing_1_1_safe_browsing.html#ae1c96b826aad62923fe10c0b10700ab3',1,'com.cujo.safebrowsing.SafeBrowsing.setHandler()'],['../classcom_1_1cujo_1_1safebrowsing_1_1_safe_browsing_message_handler.html#a8a0845057b6d883ea21f03ba71eded63',1,'com.cujo.safebrowsing.SafeBrowsingMessageHandler.setHandler(ISafeBrowsingHandler handler)']]],
  ['setinternalmessagehandler_27',['setInternalMessageHandler',['../classcom_1_1cujo_1_1safebrowsing_1_1_safe_browsing_message_handler.html#a9463b531bd6c2bc10fc27fbf03886630',1,'com::cujo::safebrowsing::SafeBrowsingMessageHandler']]],
  ['setloglevel_28',['setLogLevel',['../classcom_1_1cujo_1_1safebrowsing_1_1_safe_browsing.html#ad1372393246177350f7b0c5ffd2bfc4e',1,'com::cujo::safebrowsing::SafeBrowsing']]],
  ['setsafenetworkoverride_29',['setSafeNetworkOverride',['../classcom_1_1cujo_1_1safebrowsing_1_1_safe_browsing.html#a53ac663c5d4910ddfdc634a43299e03c',1,'com::cujo::safebrowsing::SafeBrowsing']]],
  ['snoverride_30',['snOverride',['../classcom_1_1cujo_1_1safebrowsing_1_1_s_b_types_1_1_safe_browsing_settings.html#add1ad40f0f7e803576c3a8b1f20e0b8a',1,'com::cujo::safebrowsing::SBTypes::SafeBrowsingSettings']]],
  ['start_31',['start',['../classcom_1_1cujo_1_1safebrowsing_1_1_safe_browsing.html#a1749d9188e0f33628b60913bb00922a7',1,'com::cujo::safebrowsing::SafeBrowsing']]],
  ['stop_32',['stop',['../classcom_1_1cujo_1_1safebrowsing_1_1_safe_browsing.html#aac81225296f620d1fbf3446422e0f9f0',1,'com::cujo::safebrowsing::SafeBrowsing']]],
  ['subscribetomessages_33',['subscribeToMessages',['../classcom_1_1cujo_1_1safebrowsing_1_1_safe_browsing_message_handler.html#a1ae51c5efa07503c5b411bde2b1d7e27',1,'com::cujo::safebrowsing::SafeBrowsingMessageHandler']]]
];
