var searchData=
[
  ['serverinformation',['ServerInformation',['../classcom_1_1speedify_1_1speedifysdk_1_1_types_1_1_server_information.html',1,'com::speedify::speedifysdk::Types']]],
  ['serverinformationdetailed',['ServerInformationDetailed',['../classcom_1_1speedify_1_1speedifysdk_1_1_types_1_1_server_information_detailed.html',1,'com::speedify::speedifysdk::Types']]],
  ['serversettings',['ServerSettings',['../classcom_1_1speedify_1_1speedifysdk_1_1_types_1_1_server_settings.html',1,'com::speedify::speedifysdk::Types']]],
  ['sessionstatperiods',['SessionStatPeriods',['../classcom_1_1speedify_1_1speedifysdk_1_1_types_1_1_session_stat_periods.html',1,'com::speedify::speedifysdk::Types']]],
  ['sessionstats',['SessionStats',['../classcom_1_1speedify_1_1speedifysdk_1_1_types_1_1_session_stats.html',1,'com::speedify::speedifysdk::Types']]],
  ['settings',['Settings',['../classcom_1_1speedify_1_1speedifysdk_1_1_types_1_1_settings.html',1,'com::speedify::speedifysdk::Types']]],
  ['speedifyhandler',['SpeedifyHandler',['../classcom_1_1speedify_1_1speedifysdk_1_1_speedify_handler.html',1,'com::speedify::speedifysdk']]],
  ['speedifysdk',['SpeedifySDK',['../classcom_1_1speedify_1_1speedifysdk_1_1_speedify_s_d_k.html',1,'com::speedify::speedifysdk']]],
  ['speedtestconnectionresult',['SpeedTestConnectionResult',['../classcom_1_1speedify_1_1speedifysdk_1_1_types_1_1_speed_test_connection_result.html',1,'com::speedify::speedifysdk::Types']]],
  ['speedtestresults',['SpeedTestResults',['../classcom_1_1speedify_1_1speedifysdk_1_1_types_1_1_speed_test_results.html',1,'com::speedify::speedifysdk::Types']]],
  ['speedteststatus',['SpeedTestStatus',['../enumcom_1_1speedify_1_1speedifysdk_1_1_types_1_1_speed_test_status.html',1,'com::speedify::speedifysdk::Types']]],
  ['speedteststep',['SpeedTestStep',['../enumcom_1_1speedify_1_1speedifysdk_1_1_types_1_1_speed_test_step.html',1,'com::speedify::speedifysdk::Types']]],
  ['startupbroadcastreceiver',['StartupBroadcastReceiver',['../classcom_1_1speedify_1_1speedifysdk_1_1_startup_broadcast_receiver.html',1,'com::speedify::speedifysdk']]],
  ['state',['State',['../enumcom_1_1speedify_1_1speedifysdk_1_1_types_1_1_state.html',1,'com::speedify::speedifysdk::Types']]],
  ['streamingsessionstats',['StreamingSessionStats',['../classcom_1_1speedify_1_1speedifysdk_1_1_types_1_1_streaming_session_stats.html',1,'com::speedify::speedifysdk::Types']]],
  ['streamingstats',['StreamingStats',['../classcom_1_1speedify_1_1speedifysdk_1_1_types_1_1_streaming_stats.html',1,'com::speedify::speedifysdk::Types']]],
  ['streamstats',['StreamStats',['../classcom_1_1speedify_1_1speedifysdk_1_1_types_1_1_stream_stats.html',1,'com::speedify::speedifysdk::Types']]]
];
